### ISSUE TITLE
update package

### ISSUE THREAD

**Issue by CodeDotJS** [feross/stream-to-blob-url#7]
hi @feross 

just wanted to inform you that npm's page of  [stream-to-blob-url](https://www.npmjs.com/package/stream-to-blob-url) is still showing

```toBlobURL(fs.createReadStream('file.txt'), 'file.txt',``` 
instead of
```(fs.createReadStream('file.txt'), 'text/plain',```

**Comment by feross** [comment]
Thanks -- this is fixed now!
